# Generated by Django 5.1.4 on 2024-12-09 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_meal_weighttracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='date',
        ),
    ]
